"""Render the KPI catalog (docs/kpi-catalog.md) from the registry.

Regenerate with::

    python -m app.analytics.kpis.catalog
"""

from __future__ import annotations

from app.analytics.kpis.definitions import TEMPLATE_COMPONENTS
from app.analytics.kpis.models import KPIDefinition
from app.analytics.kpis.registry import list_kpi_definitions
from app.analytics.kpis.sql import TEMPLATES
from app.config import PROJECT_ROOT

CATALOG_PATH = PROJECT_ROOT / "docs" / "kpi-catalog.md"

_RULE_TEXT = {
    "component": "value = {component}",
    "scaled": "value = {component} x {factor:g}",
    "ratio": "value = {numerator} / {denominator}",
    "complement_ratio": "value = 1 - {numerator} / {denominator}",
    "growth": "value = {numerator} / {denominator} - 1",
    "net_retention": "value = (opening_mrr - churned_mrr - contraction_mrr + expansion_mrr) / opening_mrr",
    "lifetime_value": (
        "value = (closing_mrr / closing_customers) / (churned_customers / opening_customers / period_months)"
    ),
}


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def rule_text(definition: KPIDefinition) -> str:
    rule = definition.value_rule
    return _RULE_TEXT[rule.kind].format(
        component=rule.component, numerator=rule.numerator, denominator=rule.denominator, factor=rule.factor or 1
    )


def render_kpi(definition: KPIDefinition) -> str:
    empty = (
        "an empty result means zero counts (counts report 0; ratios report insufficient_data)"
        if definition.zero_when_empty
        else "an empty result is reported as no_data"
    )
    lines = [
        f"### `{definition.key}`: {definition.name}",
        "",
        f"**Definition.** {definition.definition}",
        "",
        "| Property | Value |",
        "|---|---|",
        f"| Formula | {_escape(definition.formula)} |",
        f"| Value rule | `{rule_text(definition)}` |",
        f"| Unit | {definition.unit} |",
        f"| Time grain | {_escape(definition.time_grain)} |",
        f"| Interpretation | {_escape(definition.interpretation)} |",
        f"| Dependencies | {', '.join(f'`{d}`' for d in definition.dependencies)} |",
        f"| SQL template | `{definition.template}` (components: {', '.join(definition.components)}) |",
        f"| Filters | {', '.join(f'`{f}`' for f in definition.supported_filters) or 'none'} |",
        f"| Breakdown dimensions | {', '.join(f'`{d}`' for d in definition.supported_dimensions) or 'none'} |",
        f"| Empty result | {empty} |",
    ]
    if definition.requires_comparison:
        lines.append("| Comparison period | required (defaults to the preceding period of the same shape) |")
    if definition.required_any_of:
        lines.append(f"| Required | one of {', '.join(definition.required_any_of)} as filter or dimension |")
    if definition.insufficient_grains:
        lines.append(
            f"| Not reported at grain | {', '.join(f'`{g}`' for g in definition.insufficient_grains)} "
            "(returns insufficient_data with the reason) |"
        )
    lines += ["", "**Limitations**", "", *[f"- {item}" for item in definition.limitations], ""]
    return "\n".join(lines)


def render_catalog() -> str:
    definitions = list_kpi_definitions()
    sections = [
        "# KPI Catalog",
        "",
        "<!-- Generated by `python -m app.analytics.kpis.catalog` from app/analytics/kpis/definitions.py. "
        "Do not edit by hand. -->",
        "",
        f"{len(definitions)} registered KPIs. Each is computed by `calculate_kpi(db, key, params)` from a registered, "
        "parameterised SQL template plus a documented value rule. See [analytics.md](analytics.md) for conventions "
        "(periods, point-in-time rule, filters, result contract).",
        "",
        "| # | Key | Name | Unit | Formula |",
        "|---|---|---|---|---|",
        *[
            f"| {i} | `{d.key}` | {d.name} | {d.unit} | {_escape(d.formula)} |"
            for i, d in enumerate(definitions, start=1)
        ],
        "",
        "## Definitions",
        "",
    ]
    sections += [render_kpi(d) for d in definitions]
    sections += ["## SQL templates", ""]
    for template in TEMPLATES.values():
        sections += [
            f"### `{template.name}`",
            "",
            f"{template.description} Temporal semantics: `{template.temporal}`. "
            f"Components: {', '.join(TEMPLATE_COMPONENTS[template.name])}.",
            "",
            "```sql",
            template.sql,
            "```",
            "",
        ]
    return "\n".join(sections).rstrip() + "\n"


if __name__ == "__main__":
    CATALOG_PATH.write_text(render_catalog(), encoding="utf-8")
    print(f"Wrote {CATALOG_PATH.relative_to(PROJECT_ROOT)}")
