"""Helpers for the Phase 7 evaluation tests: a data source for a generated dataset and run fingerprints."""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

from data.generator.generate import GenerationResult
from evals.reference.context import DataSource

if TYPE_CHECKING:
    from evals.reports.models import EvaluationResult


def source_for(dataset: GenerationResult) -> DataSource:
    """The evaluation data source for a dataset generated by a test fixture (with its own ground truth)."""
    config = dataset.config
    return DataSource(
        db_path=config.db_path,
        ground_truth_path=config.ground_truth_path,
        seed=config.seed,
        dataset_version=str(dataset.manifest["dataset_version"]),
        as_of=config.end_date,
        origin="generated",
        coverage_start=config.start_date,
    )


def fingerprint(results: list[EvaluationResult]) -> list[tuple[Any, ...]]:
    """Everything a run decides, without timings."""
    return [
        (
            r.scenario_id,
            r.status,
            sorted(r.scores.items()),
            [
                (f.category, f.check, json.dumps(f.expected, default=str), json.dumps(f.actual, default=str))
                for f in r.failures
            ],
            [{k: v for k, v in t.items() if k != "latency_ms"} for t in r.tool_trace],
            r.security_events,
            r.evidence_ids,
        )
        for r in results
    ]
